// Generated by gencpp from file intersection/CarComOne.msg
// DO NOT EDIT!


#ifndef INTERSECTION_MESSAGE_CARCOMONE_H
#define INTERSECTION_MESSAGE_CARCOMONE_H

#include <ros/service_traits.h>


#include <intersection/CarComOneRequest.h>
#include <intersection/CarComOneResponse.h>


namespace intersection
{

struct CarComOne
{

typedef CarComOneRequest Request;
typedef CarComOneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CarComOne
} // namespace intersection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::intersection::CarComOne > {
  static const char* value()
  {
    return "270abad34ce1b23dffdbb99ceeeccc24";
  }

  static const char* value(const ::intersection::CarComOne&) { return value(); }
};

template<>
struct DataType< ::intersection::CarComOne > {
  static const char* value()
  {
    return "intersection/CarComOne";
  }

  static const char* value(const ::intersection::CarComOne&) { return value(); }
};


// service_traits::MD5Sum< ::intersection::CarComOneRequest> should match 
// service_traits::MD5Sum< ::intersection::CarComOne > 
template<>
struct MD5Sum< ::intersection::CarComOneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::intersection::CarComOne >::value();
  }
  static const char* value(const ::intersection::CarComOneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::intersection::CarComOneRequest> should match 
// service_traits::DataType< ::intersection::CarComOne > 
template<>
struct DataType< ::intersection::CarComOneRequest>
{
  static const char* value()
  {
    return DataType< ::intersection::CarComOne >::value();
  }
  static const char* value(const ::intersection::CarComOneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::intersection::CarComOneResponse> should match 
// service_traits::MD5Sum< ::intersection::CarComOne > 
template<>
struct MD5Sum< ::intersection::CarComOneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::intersection::CarComOne >::value();
  }
  static const char* value(const ::intersection::CarComOneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::intersection::CarComOneResponse> should match 
// service_traits::DataType< ::intersection::CarComOne > 
template<>
struct DataType< ::intersection::CarComOneResponse>
{
  static const char* value()
  {
    return DataType< ::intersection::CarComOne >::value();
  }
  static const char* value(const ::intersection::CarComOneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERSECTION_MESSAGE_CARCOMONE_H
