// Generated by gencpp from file intersection/createCarRequest.msg
// DO NOT EDIT!


#ifndef INTERSECTION_MESSAGE_CREATECARREQUEST_H
#define INTERSECTION_MESSAGE_CREATECARREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace intersection
{
template <class ContainerAllocator>
struct createCarRequest_
{
  typedef createCarRequest_<ContainerAllocator> Type;

  createCarRequest_()
    : check(0)  {
    }
  createCarRequest_(const ContainerAllocator& _alloc)
    : check(0)  {
  (void)_alloc;
    }



   typedef int64_t _check_type;
  _check_type check;





  typedef boost::shared_ptr< ::intersection::createCarRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intersection::createCarRequest_<ContainerAllocator> const> ConstPtr;

}; // struct createCarRequest_

typedef ::intersection::createCarRequest_<std::allocator<void> > createCarRequest;

typedef boost::shared_ptr< ::intersection::createCarRequest > createCarRequestPtr;
typedef boost::shared_ptr< ::intersection::createCarRequest const> createCarRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intersection::createCarRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intersection::createCarRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace intersection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::intersection::createCarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intersection::createCarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intersection::createCarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intersection::createCarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intersection::createCarRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intersection::createCarRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intersection::createCarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd2b440b511ca1d8964b537e735641de";
  }

  static const char* value(const ::intersection::createCarRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd2b440b511ca1d8ULL;
  static const uint64_t static_value2 = 0x964b537e735641deULL;
};

template<class ContainerAllocator>
struct DataType< ::intersection::createCarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intersection/createCarRequest";
  }

  static const char* value(const ::intersection::createCarRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intersection::createCarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 check\n"
;
  }

  static const char* value(const ::intersection::createCarRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intersection::createCarRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.check);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct createCarRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intersection::createCarRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intersection::createCarRequest_<ContainerAllocator>& v)
  {
    s << indent << "check: ";
    Printer<int64_t>::stream(s, indent + "  ", v.check);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERSECTION_MESSAGE_CREATECARREQUEST_H
