// Generated by gencpp from file intersection/createCar.msg
// DO NOT EDIT!


#ifndef INTERSECTION_MESSAGE_CREATECAR_H
#define INTERSECTION_MESSAGE_CREATECAR_H

#include <ros/service_traits.h>


#include <intersection/createCarRequest.h>
#include <intersection/createCarResponse.h>


namespace intersection
{

struct createCar
{

typedef createCarRequest Request;
typedef createCarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct createCar
} // namespace intersection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::intersection::createCar > {
  static const char* value()
  {
    return "81fafe211a05479f18572c2a83d88d33";
  }

  static const char* value(const ::intersection::createCar&) { return value(); }
};

template<>
struct DataType< ::intersection::createCar > {
  static const char* value()
  {
    return "intersection/createCar";
  }

  static const char* value(const ::intersection::createCar&) { return value(); }
};


// service_traits::MD5Sum< ::intersection::createCarRequest> should match 
// service_traits::MD5Sum< ::intersection::createCar > 
template<>
struct MD5Sum< ::intersection::createCarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::intersection::createCar >::value();
  }
  static const char* value(const ::intersection::createCarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::intersection::createCarRequest> should match 
// service_traits::DataType< ::intersection::createCar > 
template<>
struct DataType< ::intersection::createCarRequest>
{
  static const char* value()
  {
    return DataType< ::intersection::createCar >::value();
  }
  static const char* value(const ::intersection::createCarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::intersection::createCarResponse> should match 
// service_traits::MD5Sum< ::intersection::createCar > 
template<>
struct MD5Sum< ::intersection::createCarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::intersection::createCar >::value();
  }
  static const char* value(const ::intersection::createCarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::intersection::createCarResponse> should match 
// service_traits::DataType< ::intersection::createCar > 
template<>
struct DataType< ::intersection::createCarResponse>
{
  static const char* value()
  {
    return DataType< ::intersection::createCar >::value();
  }
  static const char* value(const ::intersection::createCarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERSECTION_MESSAGE_CREATECAR_H
