# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from intersection/CarComOneRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CarComOneRequest(genpy.Message):
  _md5sum = "2642c81ca61d90ff57b0dfdde379e953"
  _type = "intersection/CarComOneRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 inOut
int64 vin
float64 speed
float64 accel
int64 enterTime
int64 lane
int64 turn
float64 length
float64 width
"""
  __slots__ = ['inOut','vin','speed','accel','enterTime','lane','turn','length','width']
  _slot_types = ['int64','int64','float64','float64','int64','int64','int64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       inOut,vin,speed,accel,enterTime,lane,turn,length,width

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CarComOneRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.inOut is None:
        self.inOut = 0
      if self.vin is None:
        self.vin = 0
      if self.speed is None:
        self.speed = 0.
      if self.accel is None:
        self.accel = 0.
      if self.enterTime is None:
        self.enterTime = 0
      if self.lane is None:
        self.lane = 0
      if self.turn is None:
        self.turn = 0
      if self.length is None:
        self.length = 0.
      if self.width is None:
        self.width = 0.
    else:
      self.inOut = 0
      self.vin = 0
      self.speed = 0.
      self.accel = 0.
      self.enterTime = 0
      self.lane = 0
      self.turn = 0
      self.length = 0.
      self.width = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2q2d3q2d().pack(_x.inOut, _x.vin, _x.speed, _x.accel, _x.enterTime, _x.lane, _x.turn, _x.length, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.inOut, _x.vin, _x.speed, _x.accel, _x.enterTime, _x.lane, _x.turn, _x.length, _x.width,) = _get_struct_2q2d3q2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2q2d3q2d().pack(_x.inOut, _x.vin, _x.speed, _x.accel, _x.enterTime, _x.lane, _x.turn, _x.length, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.inOut, _x.vin, _x.speed, _x.accel, _x.enterTime, _x.lane, _x.turn, _x.length, _x.width,) = _get_struct_2q2d3q2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2q2d3q2d = None
def _get_struct_2q2d3q2d():
    global _struct_2q2d3q2d
    if _struct_2q2d3q2d is None:
        _struct_2q2d3q2d = struct.Struct("<2q2d3q2d")
    return _struct_2q2d3q2d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from intersection/CarComOneResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CarComOneResponse(genpy.Message):
  _md5sum = "e753458bdfec6c28c64ea4577fe4d8cc"
  _type = "intersection/CarComOneResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 requestedAccel
int64 expectedTime

"""
  __slots__ = ['requestedAccel','expectedTime']
  _slot_types = ['int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       requestedAccel,expectedTime

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CarComOneResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.requestedAccel is None:
        self.requestedAccel = 0
      if self.expectedTime is None:
        self.expectedTime = 0
    else:
      self.requestedAccel = 0
      self.expectedTime = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2q().pack(_x.requestedAccel, _x.expectedTime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.requestedAccel, _x.expectedTime,) = _get_struct_2q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2q().pack(_x.requestedAccel, _x.expectedTime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.requestedAccel, _x.expectedTime,) = _get_struct_2q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2q = None
def _get_struct_2q():
    global _struct_2q
    if _struct_2q is None:
        _struct_2q = struct.Struct("<2q")
    return _struct_2q
class CarComOne(object):
  _type          = 'intersection/CarComOne'
  _md5sum = '270abad34ce1b23dffdbb99ceeeccc24'
  _request_class  = CarComOneRequest
  _response_class = CarComOneResponse
